---
- hosts: servidor_mysql
  sudo: yes
  vars:
    mysql_root_db_pass: 'asdasd'
  tasks:
    - name: install mysql
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server
        - python-mysqldb 

    - name: Ensure mysql binds to internal interface
      template: >
        src=templates/my.cnf 
        dest=/etc/mysql/my.cnf 
        owner=root 
        group=root 
        mode=0644
      notify: restart mysql

    - name: copy .my.cnf file with root password credentials
      template: src=templates/.my.cnf.j2 dest=~/.my.cnf owner=root mode=0600


    - name: create database wordpress
      mysql_db: name=wordpress state=present

    - name: import database wordpress
      mysql_db: name=wordpress state=import target=/tmp/wp.sql

    - name: create user mysql wordpress
      mysql_user: name=user_wp host={{ item }} password="asdasd" priv=wordpress.*:ALL,GRANT
      with_items:
        - localhost
        - "0.0.0.0"

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted