---
- hosts: servidores
  sudo: yes
  vars:
    mysql_root_db_pass: 'asdasd'
  tasks:
    - name: install mysql
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - mysql-server
        - python-mysqldb 
      
    
    - name: copy .my.cnf file with root password credentials
      template: src=templates/.my.cnf.j2 dest=~/.my.cnf mode=0600
      notify:
        - restart mysql       
    
    - name: update mysql root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
      with_items:
        - localhost
    

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted