---
- hosts: servidores
  sudo: yes
  vars:
    mysql_root_db_pass: 'asdasd'
  tasks:
    - name: install mysql
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server
        - python-mysqldb 
    
    - name: update mysql root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
      with_items:
        - localhost
    
    - name: copy .my.cnf file with root password credentials
      template: src=templates/.my.cnf.j2 dest=~/.my.cnf owner=root mode=0600
      

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
