---

- hosts: webservers
  user: root
  sudo: True

  vars:
    repository_basedir: ..

  vars_files:
    - $repository_basedir/apache/vars/main.yml

  tasks:
    # Install Apache server, a default virtual host and default config files
    - include: $repository_basedir/apache/tasks/setup.yml

  handlers:
    - include: $repository_basedir/apache/handlers/handlers.yml
